# Generated by Django 4.2 on 2023-04-16 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoriaproductos',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoria')),
                ('nombrecate', models.CharField(default='', max_length=30, verbose_name='nombre categoria')),
            ],
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('idProducto', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=20)),
                ('Descripcion', models.TextField()),
                ('Cantidad', models.IntegerField()),
                ('Precio', models.IntegerField()),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriaproductos')),
            ],
        ),
    ]
