# Generated by Django 4.2 on 2023-04-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaproductos',
            name='nombrecate',
            field=models.CharField(max_length=30, null=True, verbose_name='nombre'),
        ),
    ]
