# Generated by Django 4.2 on 2023-04-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_categoriaproductos_nombrecate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='Nombre',
            field=models.CharField(max_length=40),
        ),
    ]
